version: "3.8"
services:
  app:
    build: ./infra/php
    volumes:
      - ./backend:/backend

  web:
    image: nginx:1.18-alpine
    ports:
      - 10080:80
    volumes:
      - ./backend:/backend
      - ./infra/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /backend

  db:
    build: ./infra/mysql
    ports:
      - 33063:3306
    volumes:
      - db-store:/var/lib/mysql

volumes:
  db-store: